<!-- CONTIENT LES INFOS DE CONTACT DE L'ASSO DONC LE MAIL AINSI QU'UN FORMULAIRE DE CONTACT QUI ENVOIE UN MAIL -->
<!-- CONTIENT ÉGALEMENT DES TRUCS PUBLICS COMME LE FACEBOOK OU L'INSTAGRAM -->
@extends('layouts.page_template')

@section('head')
<title>À propos de la TIPS</title>
@endsection